version: "3.4"

services:
  app:
    container_name: yacobooks-api
    build:
      context: .
    ports:
      - 8080:8080
    volumes:
      - type: bind
        source: $HOME/yacobooks_log
        target: /yacobooks_log
    env_file:
      - es.prod.env

networks:
  default:
    external:
      name: yaco_net