version: '3.2'

services:
  elasticsearch:
    container_name: yacobooks_es
    build:
      context: elasticsearch/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - type: bind
        source: ./elasticsearch/config/elasticsearch.yml
        target: /usr/share/elasticsearch/config/elasticsearch.yml
        read_only: true
      - type: bind
        source: $HOME/workspace/es_data
        target: /data
      - type: bind
        source: $HOME/workspace/es_log
        target: /log
      - type: bind
        source: $HOME/workspace/es_repo
        target: /repo
      - type: volume
        source: elasticsearch
        target: /usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx4g -Xms4g"
      ELASTIC_PASSWORD: yain
      discovery.type: single-node

  kibana:
    container_name: yacobooks_kibana
    build:
      context: kibana/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - type: bind
        source: ./kibana/config/kibana.yml
        target: /usr/share/kibana/config/kibana.yml
        read_only: true
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch

networks:
  default:
    external: 
      name: yaco_net

volumes:
  elasticsearch:
