cluster.name: "yacobooks-cluster"
network.host: 0.0.0.0

## X-Pack settings
xpack.license.self_generated.type: trial
xpack.security.enabled: true
xpack.monitoring.collection.enabled: true

#node
node.name: yacobooks-node
path.data: /data
path.logs: /log
path.repo: ["/repo/book"]
http.port: 9200
transport.tcp.port: 9300
node.master: true
node.data: true

#index
action.auto_create_index: .security, .monitoring*, .watches, .triggered_watches, .watcher-history*